import { StyleSheet } from 'react-native';
import theme from '@/constants/colors';
import { Typography } from '@/constants/typography';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.backgroundPrimary,
    },
    headerButtons: {
        position: 'absolute',
        left: 0,
        right: 0,
        zIndex: 100,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: theme.textPrimary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: theme.backgroundSecondaryVarient,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
    },
    headerRightButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    scrollContainer: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 32,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.backgroundPrimary,
    },
    loadingText: {
        marginTop: 16,
        ...Typography.body(theme.accentPrimary),
    },
    heroSection: {
        position: 'relative',
    },
    heroImageContainer: {
        width: '100%',
        height: 500,
        position: 'relative',
    },
    heroImage: {
        width: '100%',
        height: '100%',
        backgroundColor: theme.borderSubtle,
    },
    heroGradient: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 100,
    },
    changePhotoFab: {
        position: 'absolute',
        bottom: 80,
        right: 20,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: theme.backgroundPrimary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },

    addPhotoContainer: {
        width: '100%',
        height: 280,
        backgroundColor: theme.accentPrimary,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    addPhotoIcon: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: theme.backgroundPrimary,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    addPhotoText: {
        ...Typography.h2(theme.textPrimary),
        marginBottom: 4,
    },
    addPhotoSubtext: {
        ...Typography.caption(theme.backgroundSecondary),
    },
    contentWrapper: {
        backgroundColor: theme.backgroundPrimary,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        marginTop: -24,
        zIndex: 10,
    },
    content: {
        padding: 24,
    },
    titleSection: {
        marginBottom: 20,
    },
    dateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 8,
    },
    dateText: {
        ...Typography.body(theme.backgroundSecondary),
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        marginBottom: 8,
    },
    title: {
        flex: 1,
        ...Typography.h1(theme.textPrimary),
        lineHeight: 40,
    },
    authorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 8,
        marginBottom: 16,
    },
    avatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: theme.backgroundSecondary,
    },
    avatarText: {
        ...Typography.label(theme.accentPrimary),
    },
    authorName: {
        ...Typography.body(theme.backgroundPrimary),
    },
    editIconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: theme.accentPrimary,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 4,
    },
    nameEditContainer: {
        marginBottom: 8,
    },
    nameInput: {
        ...Typography.h2(theme.textPrimary),
        backgroundColor: theme.textPrimary,
        borderWidth: 2,
        borderColor: theme.backgroundPrimary,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
    },
    nameInputInDetails: {
        ...Typography.body(theme.textPrimary),
        backgroundColor: theme.backgroundPrimary,
        borderWidth: 1,
        borderColor: theme.accentPrimary,
        borderRadius: 12,
        padding: 16,
    },
    editButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    iconButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
    },
    saveIconButton: {
        backgroundColor: theme.backgroundPrimary,
    },
    cancelIconButton: {
        backgroundColor: theme.accentPrimary,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 12,
    },
    location: {
        ...Typography.body(theme.backgroundSecondary),
    },
    ratingRow: {
        flexDirection: 'row',
        gap: 4,
    },
    reviewCard: {
        backgroundColor: theme.backgroundSecondary,
        borderRadius: 16,
        padding: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: theme.borderSubtle,
    },
    reviewText: {
        ...Typography.body(theme.backgroundPrimary),
        lineHeight: 24,
    },
    statsSection: {
        flexDirection: 'row',
        flexWrap: 'wrap' as const,
        gap: 12,
        marginBottom: 24,
    },
    statCard: {
        flex: 1,
        minWidth: 100,
        backgroundColor: theme.backgroundSecondary,
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        shadowColor: theme.backgroundSecondaryVarient,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    statIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: theme.backgroundPrimary,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    statLabel: {
        ...Typography.caption(theme.backgroundSecondary),
        marginBottom: 4,
    },
    statValue: {
        ...Typography.h2(theme.accentPrimary),
    },
    tagsSection: {
        backgroundColor: theme.backgroundSecondary,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 16,
    },
    sectionTitle: {
        ...Typography.h2(theme.backgroundPrimary),
    },
    tagsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap' as const,
        gap: 8,
    },
    tagChip: {
        backgroundColor: theme.backgroundPrimary,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
    },
    tagText: {
        ...Typography.label(theme.backgroundSecondary),
    },
    editDetailsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: theme.textPrimary,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: theme.backgroundPrimary,
    },
    editDetailsText: {
        ...Typography.label(theme.backgroundPrimary),
    },
    editSection: {
        backgroundColor: theme.backgroundSecondary,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    editSectionTitle: {
        ...Typography.h2(theme.textPrimary),
        marginBottom: 12,
    },
    ratingStars: {
        flexDirection: 'row',
        gap: 8,
    },
    starButton: {
        padding: 4,
    },
    reviewInput: {
        backgroundColor: theme.backgroundPrimary,
        borderWidth: 1,
        borderColor: theme.accentPrimary,
        borderRadius: 12,
        padding: 16,
        ...Typography.body(theme.textPrimary),
        minHeight: 120,
    },
    difficultyOptions: {
        flexDirection: 'row',
        gap: 8,
    },
    difficultyChip: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        backgroundColor: theme.backgroundPrimary,
        borderWidth: 2,
        borderColor: theme.accentPrimary,
        alignItems: 'center',
    },
    difficultyChipSelected: {
        backgroundColor: theme.backgroundPrimary,
        borderColor: theme.backgroundPrimary,
    },
    difficultyChipText: {
        ...Typography.label(theme.backgroundSecondary),
    },
    difficultyChipTextSelected: {
        color: theme.textPrimary,
    },
    editTagChip: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: theme.backgroundPrimary,
        borderWidth: 1.5,
        borderColor: theme.accentPrimary,
    },
    editTagChipSelected: {
        backgroundColor: theme.backgroundPrimary,
        borderColor: theme.backgroundPrimary,
    },
    editTagChipText: {
        ...Typography.label(theme.backgroundSecondary),
    },
    editTagChipTextSelected: {
        color: theme.textPrimary,
    },
    editActionButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    actionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        borderRadius: 12,
    },
    cancelActionButton: {
        backgroundColor: theme.backgroundPrimary,
        borderWidth: 2,
        borderColor: theme.accentPrimary,
    },
    cancelActionText: {
        ...Typography.label(theme.textPrimary),
    },
    saveActionButton: {
        backgroundColor: theme.backgroundPrimary,
    },
    saveActionText: {
        ...Typography.label(theme.textPrimary),
    },
    mapSection: {
        marginBottom: 20,
    },
    mapContainer: {
        height: 260,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 12,
        borderWidth: 1,
        borderColor: theme.accentPrimary,
    },
    map: {
        width: '100%',
        height: '100%',
    },
    webMapPlaceholder: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.accentPrimary,
    },
    webMapText: {
        marginTop: 12,
        ...Typography.caption(theme.backgroundSecondary),
    },
    directionsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.backgroundPrimary,
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 24,
        gap: 10,
        shadowColor: theme.backgroundPrimary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    directionsButtonText: {
        ...Typography.label(theme.textPrimary),
    },
    detailsSection: {
        backgroundColor: theme.backgroundSecondary,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    detailsTitle: {
        ...Typography.h2(theme.backgroundPrimary),
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: theme.backgroundPrimary,
    },
    detailIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: theme.accentPrimary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    detailContent: {
        flex: 1,
    },
    detailLabel: {
        ...Typography.caption(theme.backgroundSecondary),
        marginBottom: 2,
    },
    detailValue: {
        ...Typography.body(theme.backgroundPrimary),
    },
    startButton: {
        flex: 1,
        backgroundColor: theme.accentPrimary,
        borderRadius: 16,
        paddingVertical: 18,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.16,
        shadowRadius: 12,
        elevation: 6,
    },
    startButtonText: {
        ...Typography.h2(theme.backgroundPrimary),
    },
    reviewsCard: {
        width: 140,
        backgroundColor: theme.backgroundSecondary,
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    reviewsTitle: {
        ...Typography.label(theme.backgroundSecondary),
        marginBottom: 8,
    },
    reviewStars: {
        flexDirection: 'row',
        gap: 6,
    },
    /* Map modal / fullscreen map styles */
    mapModal: {
        flex: 1,
        backgroundColor: theme.backgroundPrimary,
    },
    mapModalHeader: {
        height: 64,
        paddingHorizontal: 16,
        justifyContent: 'center',
    },
    mapModalClose: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'transparent',
    },
    fullscreenMapContainer: {
        flex: 1,
        backgroundColor: theme.borderSubtle,
    },
    fullscreenMap: {
        width: '100%',
        height: '100%',
    },
    mapModalFooter: {
        padding: 16,
        backgroundColor: theme.backgroundPrimary,
    },
    beginNavButton: {
        backgroundColor: theme.accentPrimary,
        borderRadius: 16,
        paddingVertical: 14,
        alignItems: 'center',
    },
    beginNavText: {
        ...Typography.h2(theme.backgroundPrimary),
    },
});

export default styles;
