import { StyleSheet } from 'react-native';
import colors from '@/constants/colors';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    headerButtons: {
        position: 'absolute',
        left: 0,
        right: 0,
        zIndex: 100,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    headerButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.darkGreen,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 4,
    },
    headerRightButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    scrollContainer: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 32,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
        color: colors.lightGreen,
        fontWeight: '500' as const,
    },
    heroSection: {
        position: 'relative',
    },
    heroImageContainer: {
        width: '100%',
        height: 500,
        position: 'relative',
    },
    heroImage: {
        width: '100%',
        height: '100%',
        backgroundColor: colors.border,
    },
    heroGradient: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 100,
    },
    changePhotoFab: {
        position: 'absolute',
        bottom: 80,
        right: 20,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },

    addPhotoContainer: {
        width: '100%',
        height: 280,
        backgroundColor: colors.lightGreen,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 32,
    },
    addPhotoIcon: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    addPhotoText: {
        fontSize: 18,
        fontWeight: '600' as const,
        color: colors.darkGreen,
        marginBottom: 4,
    },
    addPhotoSubtext: {
        fontSize: 14,
        color: colors.mediumGreen,
    },
    contentWrapper: {
        backgroundColor: colors.background,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        marginTop: -24,
        zIndex: 10,
    },
    content: {
        padding: 24,
    },
    titleSection: {
        marginBottom: 20,
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        marginBottom: 8,
    },
    title: {
        flex: 1,
        fontSize: 32,
        fontWeight: '700' as const,
        color: colors.darkGreen,
        lineHeight: 40,
    },
    editIconButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.lightGreen,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 4,
    },
    nameEditContainer: {
        marginBottom: 8,
    },
    nameInput: {
        fontSize: 28,
        fontWeight: '700' as const,
        color: colors.darkGreen,
        backgroundColor: colors.white,
        borderWidth: 2,
        borderColor: colors.primary,
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
    },
    nameInputInDetails: {
        fontSize: 16,
        color: colors.darkGreen,
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.lightGreen,
        borderRadius: 12,
        padding: 16,
    },
    editButtons: {
        flexDirection: 'row',
        gap: 8,
    },
    iconButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
    },
    saveIconButton: {
        backgroundColor: colors.primary,
    },
    cancelIconButton: {
        backgroundColor: colors.lightGreen,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 12,
    },
    location: {
        fontSize: 16,
        color: colors.mediumGreen,
        fontWeight: '500' as const,
    },
    ratingRow: {
        flexDirection: 'row',
        gap: 4,
    },
    reviewCard: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 20,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: colors.paleYellow,
    },
    reviewText: {
        fontSize: 16,
        color: colors.darkGreen,
        lineHeight: 24,
    },
    statsSection: {
        flexDirection: 'row',
        flexWrap: 'wrap' as const,
        gap: 12,
        marginBottom: 24,
    },
    statCard: {
        flex: 1,
        minWidth: 100,
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 16,
        alignItems: 'center',
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    statIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    statLabel: {
        fontSize: 13,
        color: colors.mediumGreen,
        fontWeight: '500' as const,
        marginBottom: 4,
    },
    statValue: {
        fontSize: 20,
        color: colors.darkGreen,
        fontWeight: '700' as const,
    },
    tagsSection: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700' as const,
        color: colors.darkGreen,
    },
    tagsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap' as const,
        gap: 8,
    },
    tagChip: {
        backgroundColor: colors.lightGreen,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
    },
    tagText: {
        fontSize: 14,
        fontWeight: '500' as const,
        color: colors.darkGreen,
    },
    editDetailsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: colors.white,
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        marginBottom: 20,
        borderWidth: 2,
        borderColor: colors.primary,
    },
    editDetailsText: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: colors.primary,
    },
    editSection: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    editSectionTitle: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: colors.darkGreen,
        marginBottom: 12,
    },
    ratingStars: {
        flexDirection: 'row',
        gap: 8,
    },
    starButton: {
        padding: 4,
    },
    reviewInput: {
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.lightGreen,
        borderRadius: 12,
        padding: 16,
        fontSize: 15,
        color: colors.darkGreen,
        minHeight: 120,
    },
    difficultyOptions: {
        flexDirection: 'row',
        gap: 8,
    },
    difficultyChip: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        backgroundColor: colors.background,
        borderWidth: 2,
        borderColor: colors.lightGreen,
        alignItems: 'center',
    },
    difficultyChipSelected: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    difficultyChipText: {
        fontSize: 15,
        fontWeight: '600' as const,
        color: colors.mediumGreen,
    },
    difficultyChipTextSelected: {
        color: colors.white,
    },
    editTagChip: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: colors.background,
        borderWidth: 1.5,
        borderColor: colors.lightGreen,
    },
    editTagChipSelected: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    editTagChipText: {
        fontSize: 14,
        fontWeight: '500' as const,
        color: colors.mediumGreen,
    },
    editTagChipTextSelected: {
        color: colors.white,
    },
    editActionButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    actionButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        borderRadius: 12,
    },
    cancelActionButton: {
        backgroundColor: colors.background,
        borderWidth: 2,
        borderColor: colors.lightGreen,
    },
    cancelActionText: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: colors.darkGreen,
    },
    saveActionButton: {
        backgroundColor: colors.primary,
    },
    saveActionText: {
        fontSize: 16,
        fontWeight: '600' as const,
        color: colors.white,
    },
    mapSection: {
        marginBottom: 20,
    },
    mapContainer: {
        height: 260,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.lightGreen,
    },
    map: {
        width: '100%',
        height: '100%',
    },
    webMapPlaceholder: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.lightGreen,
    },
    webMapText: {
        marginTop: 12,
        fontSize: 14,
        color: colors.mediumGreen,
    },
    directionsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary,
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 24,
        gap: 10,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    directionsButtonText: {
        fontSize: 16,
        fontWeight: '700' as const,
        color: colors.white,
    },
    detailsSection: {
        backgroundColor: colors.surface,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    detailsTitle: {
        fontSize: 18,
        fontWeight: '700' as const,
        color: colors.darkGreen,
        marginBottom: 16,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.background,
    },
    detailIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.lightGreen,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    detailContent: {
        flex: 1,
    },
    detailLabel: {
        fontSize: 13,
        fontWeight: '600' as const,
        color: colors.mediumGreen,
        marginBottom: 2,
    },
    detailValue: {
        fontSize: 16,
        color: colors.darkGreen,
        fontWeight: '500' as const,
    },
});

export default styles;
