import { StyleSheet, Platform } from 'react-native';
import theme from '@/constants/colors';
import { Typography } from '@/constants/typography';

export default StyleSheet.create({
  safeContainer: {
    flex: 1,
    backgroundColor: theme.backgroundPrimary,
  },
  container: {
    flex: 1,
    backgroundColor: theme.backgroundPrimary,
  },

  stickyHeader: {
    backgroundColor: theme.backgroundPrimary,
    paddingBottom: 8,
  },
  stickySearchContainer: {
    paddingHorizontal: 16,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },

  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.backgroundSecondary,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 28,
    gap: 12,
    borderWidth: 1,
    borderColor: theme.borderSubtle,
  },
  demoButton: {
    backgroundColor: theme.backgroundPrimary,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 24,
  },
  demoButtonText: {
    ...Typography.label(theme.textPrimary),
    fontWeight: '700' as any,
  },
  searchPlaceholder: {
    ...Typography.body(theme.textMuted),
  },

  largeTrailCard: {
    backgroundColor: theme.textPrimary,
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
    position: 'relative',
  },
  largeTrailImage: {
    width: '100%',
    height: 260,
    backgroundColor: theme.backgroundSecondary,
  },
  bookmarkButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: theme.backgroundSecondaryVarient,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  cardGradient: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  cardOverlayContent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 18,
    paddingBottom: 20,
  },
  overlayTrailName: {
    ...Typography.h2(theme.textPrimary),
    marginBottom: 6,
    lineHeight: 34,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  overlayLocation: {
    ...Typography.body(theme.textPrimary),
    marginBottom: 16,
    opacity: 0.95,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  overlayBadges: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flexWrap: 'wrap' as const,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(40, 40, 40, 0.8)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  badgeText: {
    ...Typography.label('#fff'),
    paddingHorizontal: Platform.OS === 'android' ? 4 : 0,
    textTransform: 'capitalize' as const,
  },
  categoriesSection: {
    backgroundColor: theme.backgroundPrimary,
    paddingTop: 8,
    paddingBottom: 16,
  },
  categoriesScroll: {
    paddingHorizontal: 16,
    gap: 12,
  },
  categoryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20, // Increase this for better touch targets
    paddingVertical: 12,
    borderRadius: 28,
    backgroundColor: theme.textPrimary,
    // THE FIX: Prevent the button from being squeezed
    alignSelf: 'flex-start', 
    minHeight: 48,
  },

  categoryText: {
    ...Typography.caption(theme.textMuted),
    ...Platform.select({
      android: {
        includeFontPadding: false,
        paddingRight: 10,
        minWidth: 50,
      },
    }),
  },
  categoryButtonActive: {
    backgroundColor: theme.backgroundPrimary,
  },
  categoryTextActive: {
    color: theme.textPrimary,
  },
  categoryTrailsSection: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  bottomPadding: {
    height: 40,
  },
  loadingContainer: {
    paddingVertical: 60,
    alignItems: 'center',
    gap: 16,
  },
  loadingText: {
    ...Typography.caption(theme.textMuted),
  },
  emptyContainer: {
    paddingVertical: 60,
    alignItems: 'center',
    gap: 16,
    paddingHorizontal: 32,
  },
  emptyText: {
    ...Typography.body(theme.textMuted),
    textAlign: 'center',
    lineHeight: 24,
  },
  placeholderImage: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.textPrimary,
  },
  searchModalContainer: {
    flex: 1,
    backgroundColor: theme.backgroundPrimary,
  },
  searchModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderSubtle,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.accentPrimary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchModalInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.textPrimary,
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: theme.textMuted,
    gap: 12,
  },
  searchModalInput: {
    flex: 1,
    ...Typography.body(theme.textPrimary),
    padding: 0,
  },
  clearButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: theme.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchModalContent: {
    flex: 1,
    paddingTop: 12,
  },
  currentLocationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 16,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 12,
  },
  locationIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.accentPrimary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  locationTextContainer: {
    flex: 1,
  },
  locationTitle: {
    ...Typography.label(theme.textPrimary),
    marginBottom: 4,
  },
  locationSubtitle: {
    ...Typography.caption(theme.textMuted),
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 16,
    backgroundColor: theme.backgroundSecondary,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 12,
  },
  suggestionIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  suggestionTextContainer: {
    flex: 1,
  },
  suggestionTitle: {
    ...Typography.label(theme.textPrimary),
    marginBottom: 4,
  },
  suggestionSubtitle: {
    ...Typography.caption(theme.textMuted),
  },
});
